# Macro file for LED-System run of MC_LYSO
#
/run/numberOfThreads 16
/control/execute construction.mac
/run/initialize
/MC_LYSO/Mode 1
/MC_LYSO/myGun/LED-System/FrontOrBack F
/MC_LYSO/myGun/LED-System/switchOnLED u
/run/beamOn 1000000
/MC_LYSO/myGun/LED-System/switchOnLED d
/run/beamOn 1000000
/MC_LYSO/myGun/LED-System/switchOnLED r
/run/beamOn 1000000
/MC_LYSO/myGun/LED-System/switchOnLED l
/run/beamOn 1000000
/MC_LYSO/myGun/LED-System/FrontOrBack B
/MC_LYSO/myGun/LED-System/switchOnLED u
/run/beamOn 1000000
/MC_LYSO/myGun/LED-System/switchOnLED d
/run/beamOn 1000000
/MC_LYSO/myGun/LED-System/switchOnLED r
/run/beamOn 1000000
/MC_LYSO/myGun/LED-System/switchOnLED l
/run/beamOn 1000000
