# Macro file for calibration run of MC_LYSO
#
/run/numberOfThreads 16
/control/execute construction.mac
/run/initialize
/MC_LYSO/my_gun/calibration/enable true
/MC_LYSO/my_gun/calibration/FrontOrBack "F"
/MC_LYSO/my_gun/calibration/switchOnLED "u"
/run/beamOn 1000000
/MC_LYSO/my_gun/calibration/switchOnLED "d"
/run/beamOn 1000000
/MC_LYSO/my_gun/calibration/switchOnLED "r"
/run/beamOn 1000000
/MC_LYSO/my_gun/calibration/switchOnLED "l"
/run/beamOn 1000000
/MC_LYSO/my_gun/calibration/FrontOrBack "B"
/MC_LYSO/my_gun/calibration/switchOnLED "u"
/run/beamOn 1000000
/MC_LYSO/my_gun/calibration/switchOnLED "d"
/run/beamOn 1000000
/MC_LYSO/my_gun/calibration/switchOnLED "r"
/run/beamOn 1000000
/MC_LYSO/my_gun/calibration/switchOnLED "l"
/run/beamOn 1000000
