# Macro file for calibration run of MC_LYSO
#
/run/numberOfThreads 16
/control/execute construction.mac
/run/initialize
/MC_LYSO/Mode 1
/MC_LYSO/myGun/calibration/FrontOrBack F
/MC_LYSO/myGun/calibration/switchOnLED u
/run/beamOn 1000000
/MC_LYSO/myGun/calibration/switchOnLED d
/run/beamOn 1000000
/MC_LYSO/myGun/calibration/switchOnLED r
/run/beamOn 1000000
/MC_LYSO/myGun/calibration/switchOnLED l
/run/beamOn 1000000
/MC_LYSO/myGun/calibration/FrontOrBack B
/MC_LYSO/myGun/calibration/switchOnLED u
/run/beamOn 1000000
/MC_LYSO/myGun/calibration/switchOnLED d
/run/beamOn 1000000
/MC_LYSO/myGun/calibration/switchOnLED r
/run/beamOn 1000000
/MC_LYSO/myGun/calibration/switchOnLED l
/run/beamOn 1000000
